# sd-server runtime configuration.
#
# Writes %LOCALAPPDATA%\stable-diffusion.cpp\config\server.ini. Prompts for
# every server-side parameter (defaulting to the current value or a sane
# hardcoded default; Enter accepts the default, `-` explicitly unsets an
# optional field). Preserves ModelsDir set by config-model.ps1.
#
# NSIS calls this with -NonInteractive plus the values collected on the
# install-time custom page (Port, Hostname, Threads, ModelsDir); other
# params fall back to existing values or hardcoded defaults. Per-model
# params (model paths, sampler, steps, cfg, dimensions, fa, offload, etc.)
# live in presets.ini and are picked at launch time by run-server.ps1.

[CmdletBinding()]
param(
    [int]$Port,
    [string]$Hostname,
    [Nullable[int]]$Threads,
    [string]$ModelsDir,
    [switch]$NonInteractive,
    # When set, dump the existing [Server] section as a UTF-16 LE INI file at
    # the given path and exit without writing anything else. Used by the
    # installer's .onInit so GetPrivateProfileStringW can surface the user's
    # previous values as install-page defaults.
    [string]$DumpIni
)

$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot "common-functions.ps1")

$configDir   = Join-Path $env:LOCALAPPDATA "stable-diffusion.cpp\config"
$serverPath  = Join-Path $configDir "server.ini"

$cur = Read-ServerIni -Path $serverPath

# ── -DumpIni: emit the [Server] section as UTF-16 for NSIS, then exit ──

if ($DumpIni) {
    if ($cur.Count -gt 0) {
        $lines = @(
            '[Server]'
            "Port=$($cur.Port)"
            "Hostname=$($cur.Hostname)"
            "Threads=$($cur.Threads)"
            "ModelsDir=$($cur.ModelsDir)"
        )
        Add-Content -LiteralPath $DumpIni -Value $lines -Encoding Unicode
    }
    return
}

New-Item -ItemType Directory -Path $configDir -Force | Out-Null

# Read-IntDefault and ConvertTo-IntOrNull live in common-functions.ps1.

# ── Resolve initial values ───────────────────────────────────────────

# Default Threads: floor(cores * 0.5), floored to 1. Matches the runtime
# fallback in resources\run-server.ps1 and the NSIS .onInit formula.
$cores = [Environment]::ProcessorCount
$defaultThreads = [Math]::Max(1, [Math]::Floor($cores * 0.5))

$curPort    = ConvertTo-IntOrNull $cur['Port']
$curThreads = ConvertTo-IntOrNull $cur['Threads']

$portVal    = if ($PSBoundParameters.ContainsKey('Port')     -and $Port -gt 0)         { $Port }     elseif ($null -ne $curPort)    { $curPort }    else { 1234 }
$hostVal    = if ($PSBoundParameters.ContainsKey('Hostname') -and $Hostname)           { $Hostname } elseif ($cur['Hostname'])      { $cur['Hostname'] } else { 'localhost' }
$threadsVal = if ($PSBoundParameters.ContainsKey('Threads')  -and $null -ne $Threads)  { [int]$Threads } elseif ($null -ne $curThreads) { $curThreads } else { $defaultThreads }
# ModelsDir falls back: -ModelsDir param → server.ini → %USERPROFILE%\.stable-diffusion.cpp\models (matches NSIS default).
$modelsDirVal = if ($PSBoundParameters.ContainsKey('ModelsDir') -and $ModelsDir) { $ModelsDir } `
                elseif ($cur['ModelsDir']) { $cur['ModelsDir'] } `
                else { Join-Path $env:USERPROFILE ".stable-diffusion.cpp\models" }

# ── Interactive prompts ──────────────────────────────────────────────

if (-not $NonInteractive) {
    Write-Host ""
    Write-Host "── sd-server configuration ──" -ForegroundColor Cyan
    Write-Host "Press Enter to accept the default; type '-' to unset an optional field." -ForegroundColor DarkGray
    Write-Host ""

    $portVal = Read-IntDefault "Port" $portVal 1 65535

    Write-Host ""
    Write-Host "Network exposure:" -ForegroundColor Cyan
    Write-Host "  [1] localhost only  (only this machine)"
    Write-Host "  [2] all interfaces  (LAN-reachable)"
    $defaultBind = if ($hostVal -eq '0.0.0.0') { 2 } else { 1 }
    $bindReply = Read-IntDefault "Bind to" $defaultBind 1 2
    $hostVal = if ($bindReply -eq 2) { '0.0.0.0' } else { 'localhost' }

    $threadsVal = Read-IntDefault "CPU threads (-t; <= 0 means physical-core count)" $threadsVal -Min 1 -Max 256 -AllowUnset

    $reply = Read-Host "Models folder (where your .gguf / .safetensors files are stored) [$modelsDirVal]"
    if ($reply) { $modelsDirVal = $reply }
}

# ── Render ───────────────────────────────────────────────────────────

if ($modelsDirVal -and -not (Test-Path -LiteralPath $modelsDirVal)) {
    New-Item -ItemType Directory -Path $modelsDirVal -Force | Out-Null
}

$threadsLine = if ($null -ne $threadsVal) {
    "Threads = $threadsVal"
} else {
    '; Threads = 8  ; optional override; sd-server picks physical-core count when omitted'
}

$content = @"
; Generated by config-server.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')
;
; sd-server runtime configuration (machine-wide).
; Per-model knobs live in presets.ini, picked at launch by run-server.ps1.
; Re-run via the "Configure sd-server" Start Menu shortcut.

[Server]
Port = $portVal
Hostname = $hostVal
$threadsLine

; ModelsDir: where .gguf / .safetensors files live; config-model.ps1 scans
; this when building presets.ini, and run-server.ps1 uses it to resolve
; relative model paths.
ModelsDir = $modelsDirVal
"@

[System.IO.File]::WriteAllText($serverPath, $content, [System.Text.UTF8Encoding]::new($false))

# ── MCP client config ────────────────────────────────────────────────
# Materialize resources\mcp-config.template.json into
#   %LOCALAPPDATA%\stable-diffusion.cpp\config\mcp.json
# so any MCP-aware agent (Claude Code, etc.) can be pointed at it without
# the user editing JSON by hand. We use forward slashes in the script path
# so it stays valid JSON without backslash escaping and pwsh accepts it.
$mcpTemplate = Join-Path $PSScriptRoot "mcp-config.template.json"
$mcpOut      = Join-Path $configDir "mcp.json"
if (Test-Path -LiteralPath $mcpTemplate) {
    $scriptDir = $PSScriptRoot -replace '\\', '/'
    $mcpJson   = (Get-Content -LiteralPath $mcpTemplate -Raw) -replace '@SCRIPT_DIR@', $scriptDir
    [System.IO.File]::WriteAllText($mcpOut, $mcpJson, [System.Text.UTF8Encoding]::new($false))
}

if (-not $NonInteractive) {
    Write-Host ""
    Write-Host "Configuration written to:" -ForegroundColor Green
    Write-Host "  $serverPath"
    if (Test-Path -LiteralPath $mcpOut) {
        Write-Host "  $mcpOut" -ForegroundColor Green
        Write-Host ""
        Write-Host "To load the MCP server into Claude Code:" -ForegroundColor Cyan
        Write-Host "  claude --mcp-config `"$mcpOut`""
        Write-Host "or merge the file's `"mcpServers`" entry into ~/.claude.json." -ForegroundColor DarkGray
    }
    Write-Host ""
}
