// server.ini schema and IO.
//
// Single `[Server]` section with Port, Hostname, Threads (optional), ModelsDir.
// run-server.ps1 reads the same file through common-functions.ps1's
// Read-ServerIni — keep the schema in sync.

use std::fs;
use std::io;

use crate::ini;
use crate::paths;

#[derive(Debug, Clone, Default)]
pub struct ServerConfig {
    pub port: Option<i32>,
    pub hostname: Option<String>,
    pub threads: Option<i32>,
    pub models_dir: Option<String>,
}

#[allow(dead_code)] // exposed for future use (CLI default fill-in)
pub fn default_threads() -> i32 {
    let cores = std::thread::available_parallelism()
        .map(|n| n.get())
        .unwrap_or(4) as i32;
    (cores / 2).max(1)
}

pub fn default_models_dir() -> String {
    let userprofile = std::env::var_os("USERPROFILE")
        .map(std::path::PathBuf::from)
        .expect("USERPROFILE not set on Windows");
    userprofile
        .join(".stable-diffusion.cpp")
        .join("models")
        .to_string_lossy()
        .into_owned()
}

pub fn load() -> ServerConfig {
    let path = paths::server_ini();
    let keys = ini::read_section(&path, "Server");
    ServerConfig {
        port: keys.get("Port").and_then(|v| ini::parse_int(v)),
        hostname: keys.get("Hostname").cloned(),
        threads: keys.get("Threads").and_then(|v| ini::parse_int(v)),
        models_dir: keys.get("ModelsDir").cloned(),
    }
}

pub fn save(cfg: &ServerConfig) -> io::Result<()> {
    let port = cfg.port.unwrap_or(1234);
    let hostname = cfg.hostname.as_deref().unwrap_or("localhost");
    let models_dir = cfg
        .models_dir
        .clone()
        .filter(|s| !s.is_empty())
        .unwrap_or_else(default_models_dir);

    let threads_line = match cfg.threads {
        Some(n) if n > 0 => format!("Threads = {n}"),
        _ => "; Threads = 8  ; optional override; sd-server picks physical-core count when omitted".to_string(),
    };

    let body = format!(
"; Generated by sd-config.
;
; sd-server runtime configuration (machine-wide).
; Per-model knobs live in presets.ini.

[Server]
Port = {port}
Hostname = {hostname}
{threads_line}

; ModelsDir: where .gguf / .safetensors files live; the sd-config GUI scans
; it when building presets.ini, and run-server.ps1 uses it to resolve
; relative model paths.
ModelsDir = {models_dir}
");

    let path = paths::server_ini();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    // Create the models dir too (matches the PS scripts' behaviour).
    if !models_dir.is_empty() {
        let _ = fs::create_dir_all(&models_dir);
    }
    fs::write(&path, body)
}
