// server.ini schema and IO.
//
// Single `[Server]` section with Port, Hostname, Threads (optional), ModelsDir.
// run-server.ps1 reads the same file through common-functions.ps1's
// Read-ServerIni — keep the schema in sync.

use std::fs;
use std::io;

use crate::ini;
use crate::paths;

#[derive(Debug, Clone, Default)]
pub struct ServerConfig {
    pub port: Option<i32>,
    pub hostname: Option<String>,
    pub threads: Option<i32>,
    pub models_dir: Option<String>,
}

#[allow(dead_code)] // exposed for future use (CLI default fill-in)
pub fn default_threads() -> i32 {
    let cores = std::thread::available_parallelism()
        .map(|n| n.get())
        .unwrap_or(4) as i32;
    (cores / 2).max(1)
}

pub fn default_models_dir() -> String {
    let userprofile = std::env::var_os("USERPROFILE")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|| dirs::home_dir().unwrap_or_default());
    userprofile
        .join(".stable-diffusion.cpp")
        .join("models")
        .to_string_lossy()
        .into_owned()
}

pub fn load() -> ServerConfig {
    let path = paths::server_ini();
    let keys = ini::read_section(&path, "Server");
    ServerConfig {
        port: keys.get("Port").and_then(|v| ini::parse_int(v)),
        hostname: keys.get("Hostname").cloned(),
        threads: keys.get("Threads").and_then(|v| ini::parse_int(v)),
        models_dir: keys.get("ModelsDir").cloned(),
    }
}

pub fn save(cfg: &ServerConfig) -> io::Result<()> {
    let port = cfg.port.unwrap_or(1234);
    let hostname = cfg.hostname.as_deref().unwrap_or("localhost");
    let models_dir = cfg
        .models_dir
        .clone()
        .filter(|s| !s.is_empty())
        .unwrap_or_else(default_models_dir);

    let threads_line = match cfg.threads {
        Some(n) if n > 0 => format!("Threads = {n}"),
        _ => "; Threads = 8  ; optional override; sd-server picks physical-core count when omitted".to_string(),
    };

    let now = chrono_lite();

    let body = format!(
"; Generated by sd-config on {now}
;
; sd-server runtime configuration (machine-wide).
; Per-model knobs live in presets.ini.

[Server]
Port = {port}
Hostname = {hostname}
{threads_line}

; ModelsDir: where .gguf / .safetensors files live; the sd-config GUI scans
; it when building presets.ini, and run-server.ps1 uses it to resolve
; relative model paths.
ModelsDir = {models_dir}
");

    let path = paths::server_ini();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    // Create the models dir too (matches the PS scripts' behaviour).
    if !models_dir.is_empty() {
        let _ = fs::create_dir_all(&models_dir);
    }
    fs::write(&path, body)
}

// Tiny date stamp without pulling in the chrono crate.
fn chrono_lite() -> String {
    let secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0);
    // Days since 1970-01-01, ignoring leap seconds.
    let days = secs.div_euclid(86_400);
    let rem = secs.rem_euclid(86_400);
    let h = rem / 3600;
    let m = (rem % 3600) / 60;
    let (y, mo, d) = ymd_from_days(days);
    format!("{y:04}-{mo:02}-{d:02} {h:02}:{m:02}")
}

fn ymd_from_days(mut days: i64) -> (i32, u32, u32) {
    days += 719_468;
    let era = if days >= 0 { days } else { days - 146_096 } / 146_097;
    let doe = (days - era * 146_097) as u32; // [0, 146096]
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365; // [0, 399]
    let y = yoe as i32 + (era * 400) as i32;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100); // [0, 365]
    let mp = (5 * doy + 2) / 153; // [0, 11]
    let d = doy - (153 * mp + 2) / 5 + 1; // [1, 31]
    let m = if mp < 10 { mp + 3 } else { mp - 9 }; // [1, 12]
    let y = if m <= 2 { y + 1 } else { y };
    (y, m, d)
}
